name: Builds
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer
        if: matrix.os == 'macos-11'
      - run: cd oclint-scripts && ./gh-actions build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            build
