name: Build Using System LLVM
on:
  pull_request:
  schedule:
    - cron:  '0 15 * * 0'

jobs:
  build-on-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get -y install libllvm14 llvm-14 llvm-14-dev llvm-14-runtime clang-14 clang-tools-14 libclang-common-14-dev libclang-14-dev libclang1-14 libomp-14-dev libmlir-14-dev
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/lib/llvm-14
          ./bundle -archive -llvm-root=/usr/lib/llvm-14
  build-on-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          brew update
          brew install llvm@14
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/local/opt/llvm\@14
          ./bundle -archive -llvm-root=/usr/local/opt/llvm\@14
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archive build
          path: |
            build
